---
- 
  hosts: centos1
  gather_facts: False
  vars_prompt:
    - name: username
      private: False
    - name: password
      private: True
  tasks:
    - name: List of vars prompt with username and password
      debug:
        msg: "username: {{ username }}, password: {{ password }}"
